action: ALERTS
alert_category: User Defined
alert_description: $alert_description
alert_domain: DOMAIN_SECURITY
alert_fields:
  actor_effective_username: recipient
  fw_email_recipient: recipient
  proofpointtapcampaignid: campaignId
  proofpointtapclassification: classification
  proofpointtapclickip: clickIP
  proofpointtapclicktime: clickTime
  proofpointtapguid: GUID
  proofpointtapheadersfrom: headerFrom
  proofpointtapheadersreplyto: headerReplyTo
  proofpointtapid: id
  proofpointtapimposterscore: impostorScore
  proofpointtapmalwarescore: malwareScore
  proofpointtapmessageid: messageID
  proofpointtapmessageparts: messageParts
  proofpointtapmessagesize: messageSize
  proofpointtapphishingscore: phishScore
  proofpointtapreplytoaddress: replyToAddress
  proofpointtapsenderip: senderIP
  proofpointtapsmtpsender: sender
  proofpointtapspamscore: spamScore
  proofpointtapsubject: subject
  proofpointtapsuspiciousurl: threatURL
  proofpointtapthreatid: threatID
  proofpointtapthreatinfomap: threatsInfoMap
  proofpointtapthreatstatus: threatStatus
  proofpointtapthreattime: threatTime
  proofpointtapthreaturl: threatURL
  proofpointtaptype: type
  proofpointtapxmailer: xmailer
alert_name: $alert_name
alert_type: null
crontab: null
dataset: alerts
description: Click Permitted
drilldown_query_timeframe: ALERT
execution_mode: REAL_TIME
global_rule_id: Production Proofpoint TAP - Clicks Permitted
investigation_query_link: ''
is_enabled: true
lookup_mapping: []
mapping_strategy: CUSTOM
mitre_defs:
  TA0001 - Initial Access:
  - T1566 - Phishing
name: Production Proofpoint TAP - Clicks Permitted
rule_id: 112
search_window: null
severity: User Defined
simple_schedule: null
suppression_duration: 1 hours
suppression_enabled: true
suppression_fields:
- fromAddress
- headerFrom
- toAddresses
- sender
- ccAddresses
timezone: null
user_defined_category: alert_category
user_defined_severity: alert_severity
xql_query: "dataset = proofpoint_tap_v2_generic_alert_raw\n| filter type = \"clicks\
  \ permitted\"\n| alter source_alert_type = type\n| alter alert_severity = _alert_data\
  \ -> severity,\n        alert_category = _alert_data -> alert_category,\n      \
  \  alert_name = _alert_data -> alert_name,\n        alert_description =  _alert_data\
  \ -> alert_description,\n        threatsInfoMap = _alert_data -> raw_json\n| alter\
  \ threatID = threatsInfoMap -> threatID\n        "
