action: ALERTS
alert_category: User Defined
alert_description: $alert_description
alert_domain: DOMAIN_SECURITY
alert_fields:
  action_file_md5: md5
  action_file_sha256: sha256
  action_local_ip: local_ip
  action_remote_ip: dest_ip
  actor_effective_username: user_name
  agent_device_domain: domain
  agent_hostname: hostname
  agent_id: cid
  deviceexternalips: external_ip
  devicemacaddress: mac_address
  fw_email_recipient: recipient
  postnatsourceip: external_ip
  prenatsourceip: local_ip
  proofpointtapcampaignid: campaignId
  proofpointtapclassification: classification
  proofpointtapclickip: clickIP
  proofpointtapclicktime: clickTime
  proofpointtapguid: GUID
  proofpointtapheadersfrom: headerFrom
  proofpointtapheadersreplyto: headerReplyTo
  proofpointtapid: id
  proofpointtapimposterscore: impostorScore
  proofpointtapmalwarescore: malwareScore
  proofpointtapmessageid: messageID
  proofpointtapmessageparts: messageParts
  proofpointtapmessagesize: messageSize
  proofpointtapphishingscore: phishScore
  proofpointtapreplytoaddress: replyToAddress
  proofpointtapsenderip: senderIP
  proofpointtapsmtpsender: sender
  proofpointtapspamscore: spamScore
  proofpointtapsubject: subject
  proofpointtapsuspiciousurl: threatURL
  proofpointtapthreatid: threatID
  proofpointtapthreatinfomap: threatsInfoMap
  proofpointtapthreatstatus: threatStatus
  proofpointtapthreattime: threatTime
  proofpointtapthreaturl: threatURL
  proofpointtaptype: type
  proofpointtapxmailer: xmailer
alert_name: $alert_name
alert_type: null
crontab: '*/10 * * * *'
dataset: alerts
description: Click Permitted
drilldown_query_timeframe: ALERT
execution_mode: SCHEDULED
global_rule_id: Production Proofpoint TAP + CrowdStrike - Clicks Permitted
investigation_query_link: ''
is_enabled: true
lookup_mapping: []
mapping_strategy: CUSTOM
mitre_defs:
  TA0001 - Initial Access: []
name: Production Proofpoint TAP + CrowdStrike - Clicks Permitted
rule_id: 65
search_window: 1 hours
severity: User Defined
simple_schedule: 10 minutes
suppression_duration: 1 hours
suppression_enabled: true
suppression_fields:
- fromAddress
- headerFrom
- toAddresses
- sender
- ccAddresses
timezone: America/New_York
user_defined_category: alert_category
user_defined_severity: alert_severity
xql_query: "dataset = proofpoint_tap_v2_generic_alert_raw\n| filter lowercase(type)\
  \ = \"clicks permitted\"\n| alter recipient = to_string(toAddresses)\n| alter alert_severity\
  \ = coalesce(_alert_data -> severity),\n        alert_category = coalesce(_alert_data\
  \ -> alert_category),\n        alert_name = coalesce(_alert_data -> alert_name),\n\
  \        alert_description =  coalesce(_alert_data -> alert_description),\n    \
  \    threatID = coalesce(threatsInfoMap -> [0].threatID),\n        account_name\
  \ = _alert_data -> accountname,\n        deviceexternalip = _alert_data -> deviceexternalip,\n\
  \        pp_sha256 = _alert_data -> actor_process_image_sha256[0],\n        pp_local_ip\
  \ = _alert_data -> action_local_ip[0],\n        pp_agent_os = _alert_data -> agent_os_type,\n\
  \        pp_dest_ip = _alert_data -> destinationips[0]\n| join type = left (dataset\
  \ = crowdstrikefalcon_xsiam_generic_alert_raw \n| filter product = \"epp\"\n| alter\
  \       \n        hostname = device->hostname,\n        domain = device->machine_domain,\n\
  \        local_ip = device->local_ip,\n        external_ip = device->external_ip,\n\
  \        mac_address = device->mac_address\n| fields user_name, user_principal,\
  \ sha256, md5, cid, hostname, local_ip, mac_address, external_ip, domain \n) as\
  \ vt (recipient  contains vt.user_principal)\n| alter user_name = coalesce(user_name,account_name)\n\
  | alter external_ip = coalesce(external_ip, deviceexternalip)\n| alter sha256 =\
  \ coalesce(sha256, pp_sha256)\n| alter local_ip = coalesce(local_ip, pp_local_ip)\n\
  | alter dest_ip = pp_dest_ip"
