dirtyInputs: true
id: 92825389-c225-4f25-81a9-5d973634aca5
inputSections:
- description: Generic group for inputs
  inputs:
  - Shadow
  name: General (Inputs group)
inputs:
- description: In Shadow Mode the Playbook will run in a testing only mode where it
    prints to the war room but will not take disruptive actions
  key: Shadow
  playbookInputQuery: null
  required: true
  value:
    simple: "false"
name: Use Case - Proofpoint Message Delivered
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: fcd8a90f-5f53-4dc4-8ade-48374a66b4ec
starttaskid: "0"
tags:
- SOC
- PoV
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b9d53d3-d66f-4715-8249-de216ec9808d
      iscommand: false
      name: ""
      version: -1
    taskid: 0b9d53d3-d66f-4715-8249-de216ec9808d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -280
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: true
    quietmode: 2
    scriptarguments:
      ignore-outputs:
        simple: "false"
      includeCampaignForensics:
        simple: "true"
      threatId:
        simple: ${alert.proofpointtapthreatinfomap.threatid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns forensics evidence.
      id: 257fa3e9-0c36-40cd-8a22-3083572750dd
      iscommand: true
      name: Get Forensic Information
      script: '|||proofpoint-get-forensics'
      type: regular
      version: -1
    taskid: 257fa3e9-0c36-40cd-8a22-3083572750dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      forensicdnsmarkdown:
        complex:
          accessor: DNS
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicfilemarkdown:
        complex:
          accessor: File
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicnetworkmarkdown:
        complex:
          accessor: Network
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicsummarymarkdown:
        complex:
          accessor: Behavior
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 17f5eec4-9b51-4074-8ddd-cd1e58c08f8b
      iscommand: true
      name: Summarize Forensic Info
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 17f5eec4-9b51-4074-8ddd-cd1e58c08f8b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 360,
          "y": 550
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: fd493027-fde4-42fe-8fd7-b362fffd03dc
      iscommand: false
      name: Foundation - Upon Trigger
      playbookId: 0c636b23-4aaa-4eb4-84d8-e2d77cc5182b
      type: playbook
      version: -1
    taskid: fd493027-fde4-42fe-8fd7-b362fffd03dc
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": -95
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Proofpoint.Report.Behavior
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9e104c65-87b3-4525-849d-2a7e577af0c2
      iscommand: false
      name: Forensic Info Exists?
      type: condition
      version: -1
    taskid: 9e104c65-87b3-4525-849d-2a7e577af0c2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
      - "20"
    note: false
    quietmode: 2
    reputationcalc: 2
    scriptarguments:
      text:
        simple: ${alert.proofpointtapthreatinfomap.threat}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 6f5df510-9ace-4c85-83aa-653de55d0bdc
      iscommand: true
      name: Create Indicator from Threat
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 6f5df510-9ace-4c85-83aa-653de55d0bdc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 850
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b9b18ac2-1779-4228-8ca6-a1ee4314025e
      iscommand: false
      name: TIM - Enrichment
      type: title
      version: -1
    taskid: b9b18ac2-1779-4228-8ca6-a1ee4314025e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${alert.proofpointtapthreatinfomap}
      indicatorType:
        complex:
          accessor: threattype
          root: alert.proofpointtapthreatinfomap
          transformers:
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: file
              toReplace:
                value:
                  simple: attachment
            operator: replace
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: url
              toReplace:
                value:
                  simple: url
            operator: replace
      reliability:
        simple: C - Fairly reliable
      score:
        simple: "2"
      vendor:
        simple: Proofpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add DBot score to context for indicators with custom vendor, score,
        reliability, and type.
      id: 4de73dd2-6ff5-43cc-82cd-822427fb707b
      iscommand: false
      name: Assign Proofpoint DBot Score
      script: AddDBotScoreToContext
      type: regular
      version: -1
    taskid: 4de73dd2-6ff5-43cc-82cd-822427fb707b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1010
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${alert.proofpointtapthreatinfomap.threat}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the overall score for the indicator as calculated by DBot.
      id: 98559a7f-7633-4618-8855-8b078a3297a8
      iscommand: false
      name: Get Indicator Scores
      script: GetIndicatorDBotScoreFromCache
      type: regular
      version: -1
    taskid: 98559a7f-7633-4618-8855-8b078a3297a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1180
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Score
          operator: greaterThan
          right:
            value:
              simple: "2"
        - left:
            iscontext: true
            value:
              simple: Proofpoint.Report.Behavior.Malicious
          operator: isTrue
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: af9b8366-3cce-474d-89a6-2704c49d90c8
      iscommand: false
      name: Remediation Required?
      type: condition
      version: -1
    taskid: af9b8366-3cce-474d-89a6-2704c49d90c8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1530
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 1fc76c73-bff0-4657-805c-c6ac8e8548bc
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1fc76c73-bff0-4657-805c-c6ac8e8548bc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 2120
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89886dee-4e3e-4c9f-8414-ad151cc66e54
      iscommand: false
      name: Analysis
      type: title
      version: -1
    taskid: 89886dee-4e3e-4c9f-8414-ad151cc66e54
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1370
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: true
    quietmode: 0
    scriptarguments:
      url:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.proofpointtapthreatinfomap.threattype
              operator: isEqualString
              right:
                value:
                  simple: url
          root: alert.proofpointtapthreatinfomap
          transformers:
          - args:
              field:
                value:
                  simple: threat
            operator: getField
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts the contents of a URL to an image file or a PDF file.
      id: 8258967f-ca94-4268-8719-4df05002ae9d
      iscommand: true
      name: Rasterize URL
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: 8258967f-ca94-4268-8719-4df05002ae9d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1030
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: true
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      url:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.proofpointtapthreatinfomap.threattype
              operator: isEqualString
              right:
                value:
                  simple: url
          root: alert.proofpointtapthreatinfomap
          transformers:
          - args:
              field:
                value:
                  simple: threat
            operator: getField
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends http request. Returns the response as json.
      id: bdd8f897-beab-434e-83f0-7cb55ef2e622
      iscommand: false
      name: Request raw HTML
      script: http
      type: regular
      version: -1
    taskid: bdd8f897-beab-434e-83f0-7cb55ef2e622
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1180
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6284baff-3fb9-461a-889d-645f171e605c
      iscommand: false
      name: Forensics
      type: title
      version: -1
    taskid: 6284baff-3fb9-461a-889d-645f171e605c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 70
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4e618c0d-6718-4b0f-85f9-d7084050e938
      iscommand: false
      name: Remediation
      type: title
      version: -1
    taskid: 4e618c0d-6718-4b0f-85f9-d7084050e938
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 370,
          "y": 1720
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3f82b702-96b0-463f-8a6f-c858b4ebb229
      iscommand: false
      name: Manual Review
      type: regular
      version: -1
    taskid: 3f82b702-96b0-463f-8a6f-c858b4ebb229
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 370,
          "y": 1870
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2495,
        "width": 850,
        "x": 20,
        "y": -280
      }
    }
  }
